name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./"
          version: "23.1.0"
